# -*- coding: utf-8 -*-
"""Python_bib_rich.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIAoHxfPG8K2Fw9RY25mKn9ztVU7E6lZ
"""

pip install rich

# https://pypi.org/project/rich/
# https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md

from rich import print

print("Todos os dias são diferentes")
print(f"A média entre 5, 10 e 15 é {(5+10+15)/3}")
print("{'Novos Inscritos': ['Alê, 'carol', 'amanda'], 'Dados': {'inscritos': 10000, 'vídeos': 200}}")

print("Todos os dias são [bold]diferentes[/]")

print(f"A média entre [red]5[/], [blue]10[/] e [yellow]15[/] é {(5+10+15)/3}")

print("{'[underline]Novos Inscritos[/]': ['Alê, 'carol', 'amanda'], [underline]'Dados'[/]: {'inscritos': 10000, 'vídeos': 200}}")

print("[on green]Hello World![/]")

from rich.console import Console

console = Console()
console.print("As casas são vermelhas!", style="yellow bold underline on red")

print(":grinning:")

from rich.progress import track
from time import sleep

for tarefa in track(range(10), "Processando..."):
  sleep(2)

from rich.console import Console
from time import sleep

console = Console()

def criar_arquivos():
  for i in range(10):
    with open(f"arquivo{i}.txt", "w") as file:
      file.write("Criamos um novo arquivo!")
      sleep(1)
      console.log(f"Tarefa {i} finalizada!")

with console.status("[green]Realizando a tarefa...[/]") as arquivo: 
  criar_arquivos()

from rich.table import Table

table = Table(title="Filmes Favoritos")

table.add_column("Nome")
table.add_column("Data de Lançamento")
table.add_column("Faturamento")

table.add_row("Piratas do Caribe", "2006", "159999")
table.add_row("Piratas do Caribe", "2006", "159999")
table.add_row("Piratas do Caribe", "2006", "159999")
table.add_row("Piratas do Caribe", "2006", "159999")

console.print(table)

from rich.table import Table

table = Table(title="Filmes Favoritos")

table.add_column("Nome", justify="left", style="red")
table.add_column("Data de Lançamento", style="green")
table.add_column("Faturamento", style="purple")

table.add_row("Piratas do Caribe", "2006", "159999")
table.add_row("Piratas do Caribe", "2006", "159999")
table.add_row("Piratas do Caribe", "2006", "159999")
table.add_row("Piratas do Caribe", "2006", "159999")

console.print(table)

from rich import layout
from rich import print
from rich.layout import Layout

layout = Layout()
layout.split_column(
    Layout(name="topo"),
    Layout(name="baixo")
)

print(layout)

